export const homeObjOne = {
  lightBackground: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Corporate Services",
  headline: "Unlimited Transactions with zero fees",
  description: "bla bla ba",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: false,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: "services",
  lightBackground: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Services",
  headline: "Our good services",
  description: "bla bla ba",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-2.svg").default,
  alt: "Car",
  dark: false,
  primary: true,
  darkText: true,
};

export const homeObjThree = {
  lightBackground: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Pricing",
  headline: "Best in the market",
  description: "bla bla ba",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-3.svg").default,
  alt: "Car",
  dark: false,
  primary: true,
  darkText: true,
};
